FROM node:16

# Create app directory
WORKDIR /easyparking-frontend
COPY package.json package-lock.json ./

RUN npm ci

COPY . .

# RUN npm run build
# # Remove dev dependencies
# RUN npm prune --production

EXPOSE 5173
# # ENV HOST=0.0.0.0

ENV VITE_ADMIN_BASE_URL http://localhost:12345/pooler/api
ENV VITE_BASE_URL http://localhost:12345/api/

ENTRYPOINT ["npm","run", "dev"]
