version: "3.7"

services:
  mongodb:
    image: mongo:5.0.2
    restart: unless-stopped
    ports:
      - 27017:27017
    networks:
      - easyparking-network
    # TODO
    # volumes:

  backend:
    depends_on:
      - mongodb
    build: ./easyparking-backend
    restart: unless-stopped
    ports:
      - 8080:8080
    networks:
      - easyparking-network

  frontend:
    build: ./easyparking-frontend
    ports:
      - 5173:5173
    networks:
    - easyparking-network
    
  nginx:
    build: ./nginx
    ports:
      - 80:80
    depends_on:
      - backend
      - frontend
    restart: always
    networks:
    - easyparking-network

networks:
  easyparking-network:
    driver: bridge

# TODO
# volumes:
#   db: