FROM bitwalker/alpine-elixir-phoenix:latest

WORKDIR /app

# set build ENV
ENV MIX_ENV="dev"

# install mix dependencies
COPY mix.exs mix.lock ./
RUN mix deps.get --only $MIX_ENV
RUN mkdir config

ARG S3_ACCESS_KEY
ARG S3_SECRET_KEY
ARG MINIO_HOST
ENV S3_ACCESS_KEY=${S3_ACCESS_KEY} \
  S3_SECRET_KEY=${S3_SECRET_KEY} \
  MINIO_HOST=${MINIO_HOST}

COPY config/config.exs config/${MIX_ENV}.exs config/
RUN mix deps.compile

COPY ./lib ./lib
RUN mix compile

CMD elixir --sname dev --cookie monster -S mix phx.server
