FROM bitwalker/alpine-elixir-phoenix:latest

WORKDIR /app

# set build ENV
ENV MIX_ENV="dev"

# install mix dependencies
COPY mix.exs mix.lock ./
RUN mix deps.get --only $MIX_ENV
RUN mkdir config

COPY config/config.exs config/${MIX_ENV}.exs config/
RUN mix deps.compile

COPY ./lib ./lib
RUN mix compile
COPY ./config/runtime.exs ./config/runtime.exs

CMD elixir --sname dev --cookie monster -S mix phx.server
